# Generated by Django 4.2.7 on 2023-11-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matches',
        ),
        migrations.AddField(
            model_name='leagues',
            name='league',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='leagues',
            name='league_code',
            field=models.TextField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='leagues',
            name='league_emblem',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='leagues',
            name='legue_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='date_of_birth',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='players',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='players',
            name='nationality',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='players',
            name='player_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='position',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='saveapp.teams'),
        ),
        migrations.AddField(
            model_name='teams',
            name='d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='saveapp.leagues'),
        ),
        migrations.AddField(
            model_name='teams',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='team',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_emblem',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='w',
            field=models.IntegerField(default=0),
        ),
    ]
