# Generated by Django 4.2.7 on 2023-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0002_delete_matches_leagues_league_leagues_league_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='d',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='games',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='l',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='points',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='w',
        ),
        migrations.AddField(
            model_name='teams',
            name='team_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_website',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='league',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='league_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='players',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='players',
            name='nationality',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(default='', max_length=20),
        ),
    ]
