# Generated by Django 4.2.7 on 2023-12-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0003_remove_teams_d_remove_teams_games_remove_teams_goals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagues',
            name='legue_id',
        ),
    ]
