# Generated by Django 4.2.7 on 2023-12-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0004_remove_leagues_legue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='legue_id',
            field=models.IntegerField(default=0),
        ),
    ]
