# Generated by Django 4.2.7 on 2023-12-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0007_alter_teams_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='season',
            field=models.IntegerField(),
        ),
    ]
