# Generated by Django 4.2.7 on 2023-12-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0010_alter_leagues_legue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='season',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
