# Generated by Django 4.2.7 on 2023-12-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0011_alter_teams_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='season',
        ),
        migrations.AlterField(
            model_name='leagues',
            name='legue_id',
            field=models.IntegerField(default=0),
        ),
    ]
