# Generated by Django 4.2.7 on 2023-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0012_remove_teams_season_alter_leagues_legue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
