# Generated by Django 4.2.7 on 2023-12-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0013_teams_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='season',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
