# Generated by Django 4.2.7 on 2023-12-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0015_players_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
