# Generated by Django 4.2.7 on 2023-12-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0016_alter_players_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
