# Generated by Django 4.2.7 on 2023-12-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0017_alter_players_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
