# Generated by Django 5.0.1 on 2024-01-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0018_alter_players_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legue_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=20)),
                ('league_code', models.CharField(default='', max_length=5)),
                ('league_emblem', models.URLField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='teams',
            name='league',
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=20)),
                ('team_emblem', models.URLField(default='')),
                ('team_website', models.URLField(default='')),
                ('season', models.IntegerField(blank=True, default=0, null=True)),
                ('league', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='saveapp.league')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='saveapp.team'),
        ),
        migrations.DeleteModel(
            name='Leagues',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
